name: Master Build

on:
  push:
    branches:
      - master

env:
  API_VERSION: 31
  JAVA_VERSION: 11

# Where will they run
jobs:
  run-tests:
    uses: araneforseti/grocery-app/.github/workflows/tests.yml@master
    with:
      api_level: 31 # Need to find a way to not duplicate these
      java_version: 11

  build-candidate:
    runs-on: ubuntu-latest
    needs: [ run-tests ]
    steps:
     - name: Checkout
       uses: actions/checkout@v3.0.2

     - name: Set up our JDK environment
       uses: actions/setup-java@v3.5.0
       with:
         distribution: 'temurin'
         java-version: ${{ env.JAVA_VERSION }}

     - name: Gradle cache
       uses: gradle/gradle-build-action@v2

     - name: build prod
       run: ./gradlew app:bundleRelease
       env:
         SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
         SIGNING_KEY_PASSWORD: ${{ secrets.KEYPASSWORD }}
         SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTOREPASSWORD }}

     - name: Decode Keystore
       env:
         ENCODED_STRING: ${{ secrets.SIGNINGKEYBASE64 }}
       run: |
         TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
         mkdir "${TMP_KEYSTORE_FILE_PATH}"
         echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/your_keystore_file.jks

     - name: Release
       uses: softprops/action-gh-release@v1
       with:
         files: "app/build/outputs/bundle/release/*"
         tag_name: "candidate"

     - name: Save Artifact
       uses: actions/upload-artifact@v3.1.0
       with:
         name: signed-artifact
         path: app/build/outputs
         if-no-files-found: error